#!/usr/bin/env ruby

require 'mysql2'
require 'yaml'
require 'pp'
require 'json'

$validpassword = 'ihateBMRS'
$clear = `clear`
reads = File.open('/Work_Space/Child.config', "r").read
reads2 = File.open('/Work_Space/Santa.config', "r").read
writes = File.new('/Work_Space/Child.config', "w")
writes2 = File.new('/Work_Space/Santa.config', "w")
pairing_read = File.open('/Work_Space/Pairing.txt', "r").read
pairing_append = File.open('/Work_Space/Pairing.txt', 'a') 


satan = []
child = []
pairing = {}

def intro
  puts <<-PARAGRAPH
Hey! We will be doing a secret Santa for the holiday season. This will include DRT and VPS.
The max limit for the gift will be 20$. Considering our teams are separated across two locations,
it's kind of hard to pick random names from a hat. So instead, lets have Ruby do it for us! 
Let's get you synced with your secret Santa!
  PARAGRAPH
end

def passphrase
  print "Please input the password: "
        $inputpassword = gets.chomp
                if $inputpassword == $validpassword
                  puts "Welcome! Congrats on not getting fail2banned!\n"
                else
                  abort('Fuck off! Access Denied Loco!')
                end
end

puts $clear

puts "\n"
puts "\n"
puts"
   .-.                                                   \\ /
  ( (                                |                  - * -
   '-`                              -+-                  / \\
             \            o          _|_          \\
            ))          }^{        /___\\         ))
          .-#-----.     /|\\     .---'-'---.    .-#-----.
     ___ /_________\\   //|\\\\   /___________\\  /_________\\
    /___\\ |[] _ []|    //|\\\\    | A /^\\ A |    |[] _ []| _.O,_
....|\"#\"|.|  |*|  |...///|\\\\\....|   |\"|   |....|  |*|  |..(^)....
"
puts "\n"
puts "\n"

puts "#{Time.now}"
puts "\n"
intro
sleep 3
puts "\n"
passphrase

# Child IN
reads.each_line do |add|
  add.gsub!("\n","")
  child.push(add.downcase.capitalize)
end
# Satan IN
reads2.each_line do |add|
  add.gsub!("\n","")
  satan.push(add.downcase.capitalize)
end

sleep 2
puts $clear

puts "\n"
puts "\n"
puts "                                    .
                        .       *
                              |         *
                   .    *         .            *
                                          /
                *      .       ,    *          .    *
                               `;.
                      *   -      ;:,   -    *     -   .
              .  -               ,:;:,
                     .          ,:;%;;:,           *
                          /    ::;%#%;::   *    .
                   *           ::;%#%;:'
                                `:%#%'  .   .,,.
                         *    .    #     .,sSSSSs
                                   #  .,sSSSSSSSS
                                .,sSSSSSSSSSSSS'
                           .,sSSSSSSSSSSSSSSSSSs,
                       .sSSSSSSSSSSSSSSSSSSSSSSSS
                       sSSSSSSSSSSSSSSSSSSSSSSSS'
                       `SSSSSSSSSSSSSSSSSSSSSSS'
                       sSSSS;nww;SSS;mwwwn;SSSSs
                       `SSS;nnw;sSSSs;wwwnnn;SSSs
                      .sSS;nnnw;SSSSS;wwwnnn%;SSS
                     .SSSS;nnnww;SSS;mwwwnnn%;SS'
                     SSSSS;nnnwwwmmmmmwwwnnn%%;
                     `SSS'%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
                        ;%%nnnwwwmmmmmwwwnnn%%;
      ,                 ;%%nnnwwwmmmmmwwwnnn%%;
   .,;;;,.,;            ;%%nnnwwwmmmmmwwwnnn%%;        ;     ;
     `;;;;,;;;,.,;      ;%%nnnwwwmmmmmnnnnnn%%;  ,    .;;,.,;;;.
      ;;;;;;;;,;;;;;,., ;%%nnnnnnnnn;,ooo,;n%%;   ;;;;;,;;,;;,;;;,.
      ;'   `;;;;;;,;;;;.;%%nnn;,ooo,;OOOOO;n%%;  .;;,;;;;;;;;;;,;;'',
            ;'  ';;;;,;;,...   OOOOO;`OOO'..,,;,;;,;;;''';;;''';;'
                  ';;'    '''''`OOO'OOooo' ''' ;'   '     '     '
                   '         ;,.,;, `OOO'
                         ;,.;;';;;';,;.
                     ;,.;;';;;;;;;;;;;'
                   .,;;;;;;;;;;;;;;;'
                     ';'  ';'   ';;
                                  `"

sleep 1
puts "\n"
puts "Welcome to the Christmas Secret Santa! The rules are simple. You will type in your name and you will receive a team member for the $20 secret santa!\n"
puts "Be sure to select your correct name from the list below: \n "
puts "\n"
puts reads2


loop do 
  print "\nWhat is your name? >  "
  @user = gets.chomp.downcase.capitalize
  puts = "\n"
  break if satan.include? @user
  puts "\nThat name is used/unavailable.\n"
  sleep 1
end

satan.delete(@user)
puts "\nTime for the fun! Let's spin the wheel of Satan to see who you get...\n"   
sleep 1

10.times {
  print "/"
  sleep(0.1)
  print "\b"
  print "-"
  sleep(0.1)
  print "\b"
  print "\\"
  sleep(0.1)
  print "\b"
  print "|"
  sleep(0.1)
  print "\b"
}

@random = child.sample
until @random != @user
  puts "You got yourself breh, lets spin the again..."
  sleep 1
  @random = child.sample
end

puts "\nYou received #{@random} as your secret Santa!\n"
child.delete(@random)
sleep 1
puts " < :............Updating.............: > "
sleep 1
puts "\n"

pairing[@user.to_sym] = @random

print "Last time to write down who you received: "
puts pairing[@user.to_sym]

sleep 3
child.each do |w|
  writes.write("#{w}\n")
end

satan.each do |w|
 writes2.write("#{w}\n")
end

pairing_append.write("#{pairing}\n")

puts "\n"
puts "Brought to you by Luis.G and Shane.T!"
sleep 2
puts $clear

str = <<END
yyyyyyyyyyyyyy+..-.-/yyhdddhdmddhymhmsommNmmmddhsssyyhhhhdhhhhhdmmNNNNmmhhhsosyyysyhhyyyyssssssssssssssssssyyyyyyyyyyyyyyyyyy
mddddddhhhhhhho..--+dmsdhddddddmdhmmmdsodNNmNNmmdyoosssyyyyhhyhhhhdddmmdhhhmhyyhdhyyhyhdhhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
Nmmmmmmmmmmmmmy---+ddhhhyyddhddddddmmmmhoshhNNNmddhyoososooosossysoossosyssyhdyyhhddyyydddmmmmmmmmmmmmmmmmNmmmmmmmmNmNNNNNmmN
NNNNNNNNNNNNNNNdhydmdmmdyyyhyhhddddddddddyssshddddhyhyyyssssysosyysssyyhhddhhdhhhhhddhsydddhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhh
dNNNNNNNNNNNNNNmhddmmmmhyssyhhhhddddddddddhyyyyyyyyyssosyysyyyhhhhhyhhhhhddmddddyhyhddhsyhhdhs++syyssssssssssssssssyyyyyyyyyy
hmNNNNNNNNNNNNNmmmdmmddhssyhhyyhhhhhhddddddhhhhysssossyhhhhhyyyyhyyyyyyyyyyhhdhhyyhhdmdhsyddNms:+s+//////////+++++++++ooooooo
hmNNNNNNNNNNNNmNNNmddydhysssysyyyyyyhhyyyyyyyhhhyyyyyyysoooooooooooossssssssyyyhhhyyhddddyyhdNmy/:-------------:::::://////++
ymNNNNNNNNNNNNNNNNNddyhyyssyyyhhhhyyyyyhhhhhhyyyyssso+++/////////++ooooooooossssyhhhhddddyyhdNmyyo::-`````````````````::/yhhh
ymNNNNNNNNNNNNNNNNNdhysoshdddhhhhhhyhhyyyysssssoo+///:::::::::::://///+++++++++oossyyhhhhhyhddmhy+:-.                 -.:MMMM
:sNNNNNNNNNNNNNNNNNdyossyyyysssysssyyssssooo++//::----------------:::::////////++++ooosysssyhhydhho-.                 -.:MMMM
 :mNNNNNNNNNNNNNNNdsoyoyyssssoossosoo++///:::----------------------:::::::::::::///+++oooossss+yhhdy-                 -./MMMM
+hNNNNNNNNNNNNNNmds/s+oyo+ossssoooo+//:::-------.--------------------::::::::::://///+++oooossoyyhmdh.                -./NNNN
ymNNNNNNNNNNNNNmmyo:s++++ssso++////::::----------.-------------------::::::::::::://///++++oosssyhdhmy.               :.-o+//
hmNNNNNNNNNNNNNmds/:+s++ssso++///:::-----------------.--------------:::::::::::::://///++++++ssshyyhdhhs-`          `smd/-.  
dNNmmddmNNNNNNNdy+o//ososoo+//:::::----------------...--------------::-::::::::::::///+++++oooshsyyhhdmmdy/.         yNN/.`  
NNNNNNNNNNMNNNmysss/o+os+o+++::::-------.....-----.....------------------:::::::::::///++++ooossoohydhmNNNmdy:`      /NNh+.  
NNNNNNNNNNNNNNdooo+ss///os+s/::------...................------------------------::::////+++++ossoyhydhdmNNNNNdyo:` -mNNNNNm/`
NNNNNNNNNNNNNmh+oooooo--//++:-----....---..............---------------------------:::::///+++oossshyyhymNNNNNNNNNNmNNNNNNNNNm
NNNNNNNNNNNNNmy+o+//s+---:/:--...-/++++++++++++/:---------------------------::::/+++//+++++++ooyssyyyshNMMMMMMMMMNNNNNNNNNNNN
NNNNNNNNNNNNNdso++//+/-:.:/-...:+syyyhhhhhhhhhhyso++//:::---------------::+oosyyhhhhhhhhhhsooooyysosyyydMMMMMMMMMMMMNNNNNNNNN
NNNNNNNNNNNNNdo+++///::..+:..-/++++///+++ooossyyyysso+//:::::::::---:::/+ossyyhhddddddmmmmdhoosyhsssyhhdmNMMMMMMMMMMMNNNNNNNN
NNNNNNNNNNNNNd+++::::--.:/-.-:/:----:::://///////////////::::::::::::///+++oossssssssoooosshhysyhyyyyhhmNMMMMMMMMMMMMMNNNNNNN
MMMNNNNNNNNNNmo++:--:---/:.-::-----:://++++o++++/////::::::::::::://///++++++oooooo+++++++++shhyhhyyhhhmMMMMMMMMMMMMMMMNMNNNN
MMMMMNNNNNNNNNooo::-:-://-.--..--:/+ossyyhhhhhysoo++///:::---::::://++++oooosssssssooooo+++++ohydhysyhhmMMMMMMMMMMMMMMMMMNNNN
NMMMMNNNNNNNNdo++/:::+o/-....--:/+syyyhyysssyyyhhyooo++//:-----::/+oosssssssyhhhhhhhhyyssooooosyhhyyyhhNMMMMMMMMMMMMMMMMMNNNN
NMMMMMNNNNNNms+oo+://oo-.....-:/oyyhy+:/osyysoosyyysoo+//:-...---/oyssyyyyyhhhyyyyyyhdddhyssoooyhhyyyhdNMMMMMMMMMMMMMMMMMMNNN
MMMMMMMNNNNNdh++o://oo:.....--/+ssys-.-yddmmddo+ssooo++//:--..---:+yyyyyyyhyyooydddhsoydmdysssssydyyyhmMMMMMMMMMMMMMMMMMMMMNN
MMMMMMMMNNNNNds////+o/......-:/+o+/+-..yhdmmddoossoo////::------::/syhyyyyhhsodmhmmmmooyhdhysssssmhyyhmMMMMMMMMMMMMMMMMMMMMMM
NNNNMMNNNNNNdo///::oo:......-:///::://:+syyyyssssoo+//::--------::/+oyyyyyyyyyhddmmhhssyhhhyyssssmdyydmMMMMMMMMMMMMMMMMMMMMMM
NNNNNNNNNNNy::::://s+.......--------::///+oosssssoo+::-----------:/+++osyyyyyyysyyyyssyyyyyyyssoommyyymMMMMMMMMMMMMMMMMMMMMMM
NNNNNNNNNNm:oso/-/os:........--------:::/++ooooo+/:--------------:/++++++osyyyyyyysssssssssssooooddhyyhMMMMMMMMMMMMMMMMMMMMMM
NNNNNNNNNNy/so+/:+yo...........------:://+++++/:-----------------:/+++++///+ossssssssoooooooo+++ohdhddhMMMMMMMMMMMMMMMMMMMMMM
MNNNNNNNNNo/so+--+y/............----:::://:::-------------------:::/+++++//////++ooooo++++++++++oydddhmMMMMMMMMMMMMMMMMMMMMMM
MMNNNNNNNM+/so:.-+y:............---------------------------------:::/+++++///:::://////+++++//++oydddhMMMMMMMMMMMMMMMMMMMMMMM
MMMMMNNNNNy/oo--/oy:.............-------------------------------::::/+++++++////::::://////////+oyddhmMMMMMMMMMMMNNNNNNNNNNNN
MMMMMMNNNNNs/o-/osy+...............--------------::------------::///ooo++/+o++////:::::///////++ohdhdmmmmmddmmddddddddhhhhhhh
MMMMMMMMMNNN++-/oyyo-..............------------::::-...-:/+o+::///+shyso+++oso+///:::::///////++odhhddddhdhmdhhhhhhhhhhhhhhhh
MMMMMMMMMMMNm/-:oyhy:................--------::::::.-:/shdmhyo:///smNNdhyoooso++/////////////+++omdmmmmmmmmNmmmmmmmmmmmmmmddd
MMMMMMMMMMMMMy::/ohh+................-----::::::::::/+oooso////+/ohhhhyyysoo+o++///////////++++osNNNNNNNNNNNNNNNNNNNNNNNNNNNN
MMMMMMMMMMMMMN///ohhs-................---:::::----:::/+/+o+++oooosysyhhhyso+++oo+/////////++++ooyNNMMMMMMMMMMMMMMMNNNNNNNNNNN
MMMMMMMNNNNmmms:-ohdy:..............----:::::----::/++ossssyyhhyhhddddddhysoooooo++///////++ooosdmmMMMMMMMMMMMMMMMNNNNNNNNNNN
Nmdddddhhhdddd+-:+ydd+:--..........----:::::::::/++osssssoyyyhhhddddddhhhhyyyysssso+///+++++oossNdyNMMMMMMMMMMMMMMMMMNNNNNNNN
NmmmmNNNNNMMMd-/sydmds/:--.........---:::///+++oooosssssosshddddhddhhhhyyyhhdhhhhhyo++++++ooooshNNydMMMMMMMMMMMMMMMMNNNNNNNNN
MMMMMMMMMMMMNs/shdhydy//:---......---:/++o+ooooos+oo++++++/+ooooooooooooosyyhhddddhyo++++ooossymNNmdMMMMMMMMMMMMMMMMMMNNNNNNN
NNNNmmmdddhhh++oyh+/yy++//:--....----:+oooossooo+/////////+++osoosssssssssssyhdddddhyo+ooossyymNMNmNMMMMMMMMMMMMMMMMMMMNNNNNN
ssssssssssssssoo+::+sy+/:::----------/osoooooo++//++ooooooossssssssyyyyyyyyyyhhhhhhhso+ossyyyhdmmmNMMMMMMMMMMMMMMMMMMNNMMMNNN
oooooooo+++ohdho++oyhdy+:::-::::-----+sysooossoosyyhs//s:-://+:://o++oysymmdhyyyyhhyyssosyyhhmddmNMMMMMMMMMMMMMMMMMMMNMMMNNNN
+++++++++oydddmmmmmmmmho/::::::::::::/ossssssydmNmmdyhhhysssyhssyydddmmmNNmdysyyyhysssysyhhhmNmmNMMMMMMMMMMMMMMMMMMMMMNNNNNNN
/////////ydmmmmmmmmmmmdy+////://+:::://syyso+//osooosssyyyyhhhhhhhhdhhhhhhhyssyyhysssyyhhhhmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMNNNN
+///::+sdmmmmmmmmmmmmmmossoo+/oo/////+oooo+//::::///////+++oosssssssssyyyyyssyyhhhyyyhhhhddNMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMN
ysssoydmmmmmmmmmmmddddd:/ysooo+++++++sysoo+/::::::::////++++ooooooossyyyssssssyyhhdhhhdhdmNMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNd
yyhhdmmmmmmmddddddmmmmd--+ysyssosooosssyys+/+/:::::////++oossssssssyssyyyyyyyyyhhhhddddmNNMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMNhh
hdmmmmddddhyhmmmdmNNmmy..-+yssyysysossyyso+oo+/++//+oosyhddddddddddddhhhyyyyyhhhdmmddmmNNMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMNsyh
dhhyyhhhysydNmy/dmhyso+----/yyyyyssssossssoooo+++++++osydmmmmmmmmNmdmdhyyyyhhddddmmmmmNMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMs+hd
yyyhhyyssyhmho//dyoo++/----:/oyyyyyssssyysssoooo+++//+oyhhddmmmmmmmdhyssyyhhdddmmmmmmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo+dd
yydhyyyyyyddoo/:hso+///------:+yhhyyysyyyyyysso++++/++osyyyddddhdmdhyyyyyyhdddmmmmmNmdmmmddmmNNNMMMMMMMMMMMMMMMMMMMMMMMNssyhh
yddhhyyyyyddo/::sso++//-----::/++yhhhhhyyyysoossss+osssssyhhhyyyhhdhhhyhydddmmmNNmhdNmdmNmdddddddmmNNNMMMMMMMMMMMMMMMMMd+shdd
hddhhhyyyhddo::-/sso+/:-----::://+shddhhhyysssyhhysssysssyhhyyyhhhdhhhddhmmmmmNdhysymmmmmmmmmmmddddddddmmNNMMMMMMMMMMMMhyosyd
hddhhhyyyyhds:--:/yso+:------::///+osyhddhhhhhhhhddyhhysshhhhhhhhhhhhdmmmmNNmdhssyosdmmmmNmmmmmmmdmmddddddddmmNNNMMMMMNhmhyyh
hddhhyyyyyhdy/-...oys+:-------::://+++sydddddddhhddhhhyyyhhhdhdhdhdddmmNNNmmysssssoohmmmmNmmmmmmmmmmmmmmddddddddddmmNMmshddmd
hddhhhyyyyyhho:....oso:-------:::::///+sosyhddddddmdddhhyydhdddddddmdmmmmdysoossysooymmmmmmmmmmmmmmmmmmmmmmddddddddddmdyhdhdm
hdmhhyhyyyhhhyo:...-ss:----------:::://++++osyhhddmmmmmddmmmmmmmmmmmddhysooooosshsooymmmmmmmmmmmmmmmmmmmmmmmmdmddddddddddmymN
hhddhhhhhyyyhhyo:..`-s/-----------:::/:///++/+ossyhhdddmmmdmmmmddddhhssooooooosshsooymmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdmm
END
str2 = <<END
hhhhhhhhhhhhhhhhhhhdmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhhhhdmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdhhhhhhhhhhhhhhhhhhh
hhhhhhhhhhhhhhhyhmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdddddddddhhhhhhhhhh
hhhhhhhhhhhhhhhhmmmmmmNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNNNNNNNNNNNNNNmm
hhhhhhhhhhhhhhhdmmmmmNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNN
hhhhhhhhhhhhhhhmNmNmNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdddddddddddddddd
hhhhhhhhhhhhhhdmNNmNNNNNmNNNNNNNNNNNNNNNNNNNmmdddhhyyyyyssyyyyyhhdmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmhyyyyyysssssssss
yyyyyyyyyyyyyhmmNmNNNNNNmNNNNNNNNNNNNNmmhhsoo++/////////::://::////++osyhdmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdhdddddhhhhhhhhh
ysssssssssssshmmNmNNNNNNmNmmNNNNNNmmdhyso++///:::::::::::::-----:--:::::///+oydmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNMMMMMMMMMMMMMM
ysosssoooo+++dNNNmNNNNmmmNNNNNNNmdddddhyyysso+//:::::------------------::::://+osydmNNNNNNNNNNNNNNNNNNNNNNNNNNmdddddddddddddd
ysyhddyoo+++omNmNNNNNmmNNNNNNmmmdddmmmmdddddhhys+//::::--------------:://+oossssssyyhmmNNNNNNNNNNNNNNNNNNNNNNNmhhhhhhhhhhhhhh
hddmNNmddddmdmNNNNNmmNNNNNNdhyyysssssyyhhhhhyyyso+//:::::::::------::+oyhhhdddddddddhdddmNNNNNNNNNNNNNNNNNNNNNNdddddddhhhhs+/
yysssoooohmddNNmNmmNNNNNNmhso++++////++++ooooooo+++///::::::::::::::/osssyyyhyyyyyyyssssyhdmNNNNNNNNNNNNNNNNNNNdhhyyyyyyyyo::
ddmmmmNmNNNyhNNmmmNNNNNNdhso++++oossssssyyyyssoo+++++//:::::::::::://+++++ooo++++////::://+ohmNNNNNNNNNNNNmmNNNdhhhsoooooo+:-
mmmdhNNNmNNNmNNmmNNNNMNdysoooooyyhhysssssssyyyysoooo++///:::::::://++++oosyyyyyssooo++//////+sdNNNNNNNNNNNdmNNNmhhhsoooo+//--
mmmmmNNmmmNNNNmmNNNNMNdysoooooyhhho/:+yhhdhs/+yysoooo+++/:::-:::///++oosyhyysooossyyysso++///+sydNNNNNNNNNNNNNNmhhhso+++//-  
NNmmmmmNmmNNNmmNNNNNMmysoo+++oyyyso/:yhhdhyh/:+oysooooo+/::---::///++osyso/:+shhso/+shhhso+++++oshNNNNNNNNNNmNNmyyyo++/+++-  
mmmmmmmNNNmNNmNNNNNMNhsoo+++ossysssoooyddhhs++osssooooo+/:----::////+oos++:/hhhhyyo-:osysoo++//++oyNNNNNNNNNNNNmyss+++oo++.  
mmmmmdmmNNmNNNNNNMMMdysoo+++oooooooooooooooooooooooooo+/::----:://///+oooo++shdhhh+//+ooooo+/////+oymNNNNNNNNNNdyhhsoooo++.  
mmmmmmmmNNNmNNNNMMMNhsoo++++++++oo++++++++ooooooooooo+/:::-----:://///+ooooooooo++++++///////::://+oymNNNNNNNNNhhhhsooo+++.  
mmmmmmmmNNNNNmNNMMMmysoo+++++///++++++++++++++++++oo++/::------::::::://++oo++//////////::::::::://+shNMNNNNNNmdddds+oo++/. .
mmmmmdmmmNNNmmNNMMMdyso++++///////////////+///++++++++/::--------::::::::///+///////::::::::::::://+oydNMNNNNmmddhhs/:++++/``
NmmNNmmmmNMNNmNMMMNhso++++/////////////////////++++++//::------::::::::::::::::::::::::::-:::::::///+symMMNNmmmmmmmho+oooosdd
NNNNNNNNNNMNNNNMMNNhso+++//////////////////////++++++/::-----::::::::------:::::::::::-----::::::///+oymMMNNmdNNNNNdooooosyoh
dddNmNNNmmmdhmNMNmmhoo++++/////////////////////+oo++/::------::::::::---:----:::::-------:::::::://++oymNMNNNmNNNmmhoooo+ss/+
yyhmmmNNNmmmhmNNNmmhoo++++/////////////:://///+o++//::::------::::/://:::-------:::::-::::::::::///++oymNMMNNmNNNmmho+o/++s+-
NNNmmmNNNmNmhdNNNmmhso+++++++/////////::////+o+++++//::-::-----::::::/+:::::----:::::::::::::::///++oohmmNMMNNNNhhhy/+oossy+y
NNNNNmmmNNNNdmNNNdmdyo+++++++////////:://///ooo++ooo+/:::/::::::::::::o+/::::---:::::::::::://///++oosdmmMMMNNNhymmdsoosyddh+
NNNNNNNmmms++++mNdddyoo++++++/////////://///+ooosyhdhs+//++//+syyso++++++/::::::::::::::::://////+oosyddmNNMMddhdddo+yssyhhh+
NNNNNNNNNNdo/+/+dddmhso+++++++//////////////++osysssyysoooo+osyssssso+//++/:::::::::::::////////+oosyhddmNNMNhhhhdhhhhhhhhhhh
NNNNNNNNNNNd:.--+hdddso++++++++///////////+++ossyhhyyysoooo+ooooosso+////+///::::::::://///////++osyhhhdmNMNdhhhhdhhhhhhhhhhh
NNNNNNNNNNNN+..-:ydddhoo++++++++////////+++ooyyhdddddhyyysyysyyyyhhyyo+///////::::::///////+/+++osyhddyhmmdhhhhhhdhhhhhhddddd
NNNNNNNNNNNs....:oddddso+++++++++++/++++oosshhdmmmmmddddddddhhhhhdhhhhyo+//////:::://////////++osyhddddddddhhhhhddddddddddddd
NNNNNNNNmds.....-+ddddyoo++++++++++++oossyhhddmmmmmmmddddddddddddddddhhyss+/////::://///////++ooyhhddddddddddddddmdddmddddddd
NNNmddddds/:-....+ddmdyooo+++++++++oosyhhdddmmmmmmmddhyhdddddhhhhdddddhhhys++///:////////+++++oshhhddddddddddddddmdddmNmddddd
Nmdhhdddh/--.`.../hdmdhsooooo++++++oyddddhddddmmmdhyssossssssyhhhddddddddhhys+//://///////++++oyhhdddddddddddddddmdmmNNNmdddd
ddddmmmd/...``...:hdmmdyooo++++++++oydhhhhhdhdddmhysssssoosoossyhhdmmdddddddys///////////++++oyhdddddddhhhhhhhhhhhmNNNNNNNmmd
mmNNNmm+...```.../hddmdhsooo++++++++ydhyyyhddmmdmmmdyssydsossyhdddddddhdddddhyo//////////+++oohdddmdddddhhhhdddddddmNNNNmmmmN
NNNNNNms-.````-/yyhdddmdsooo++++++++oyyysssyhhhhhhhhhhddmdhdddddmmmdhhhyhyyhhy+//////////++ooydmdmmmmmdmddddmmmmmmmmmNNNmmmmd
NNNNNdyys/--:+hhssydmdmmhsoooo+++++++osyssoosyyysysssssssssyyyyyyyssssoossyyh+////////+++++oshdmmmmmmddmmhsyhdmNNNNNNNNNNNNNN
NNNNdysys+/+++++osydmmmmmyooooo++++++ooooooooossoooo++++o+++oo+ooooo++/++oys+//////+++++oooyhmmmmmmmddhdddsooosydNNNNNNNNNNNN
NNNNds+:://+//+osyydmmmmmdysooo+++++osooooooooooooooo++oo++++++++++/////++o+//////+++++oosyhdmmmmmdmmdysssyysssyhdmmdhdddhyys
NNNms:://+++++oossdmmmmmmmdysoooo++osyssooooossssssssssssssoooo+++//////++////////+++++oyhddmmmmmddddddo+ssyyyyyyyyyyyyyysso+
Nmy:-///ssyysyyshmNNmmmmmmmdhsooooossyyyyssoossyyhyhhdhyhyyyyyssoo+////+++++////++++osshhddmmmmmmmmmhdmds+///oossso+++o++sssy
h/-://+++oo+ohdmNNmyyhddmmNNmdhyssyyyyyyyyysssyhhddddddddddhhyyysso+/+oossso+///+osshyhdmmmmmmmmmmmmmdddhsooooooooossssosssss
--//:::/++/+shNMMmooohdddmNNmmddhhhdhhhhhhhyhhhdmmmmmmmmmmddddhyys++osyyyhyso++osyhdddmmNmmNmmdmmmmmdhyyyhsossssssyyyysssssss
/oo/++oo+//osdMMNy+++hdhdmNNNNNmmmdddddddhhhhhddmmmmmmmdmdddhyyysoossyyyhyyyssshhddmmmNNNmmmmmmmNmddhs+shhyooo+++oso+sssyyyoo
yhyysssysssyymMMNy//+yyhmmmmNNNNNmNmmmmmdddddddmmmmmmmmmdmmdhhyhhyyyyyhhhhhdhdddmmNNNNNNNmmmmmddNmhyo+++ysssssoosso+/+o/+ys//
ysyo///++oyyhdMMNd+/osyyhhdmmNNNNNNNNNmNmdddmmmmmmmmmNmmmmmdhhdhhhdddddddddmmmmmNNNNNNNNNmmmdmddmhssssssshsyo+o/++////o+/+os+
oooo+oooo++oydNMMNs+++syyyddmmmNNNNNNNNNmmmmmmmmmmmmmmmmmmmddddddddmmmmmmmmmmmNNNNNNNNNmNmmdddmmdssyhhhhyyysyoooooo++/+o//++o
/+ssyssyyyssssdMNNNy++osyyhdmmNNNNNNNNNmmNmmNmmmmmmmmmmmmmmddmmmmmmmmNmmmmNNNNNNNNNNNNNmNmddddNMhhhhddhsoosyyhhyssssso:oo++++
/++oooossyyyyyhNNNNNhooooshdmNNNNNNNNNNNmNNmNNmmNmmmNNmmmmmmmmmmmmNNNNNNmNNNNNNNNNNNNmmNmmdhhmMNddhhhysossysooyo///++o:oso++/
+:-::/++ooossysdMMNNNdsssyhdmmNNNNNNNNNNNNNNNmmNNmNNNNmNNmNmmmmNmmNNNNNNNNNNNNNNmNmmmmmmmdyhmMMNdhyysosyhyso+++o+/:::::+syo+/
:-------:::/+o+sNMMMMMNhysydmmmNmNNNNNNNNNNNNmmNNNNNNNNNNmNNNNNNmNNNNNNNNNNNNNNNmddmmmdmdhdNMMNmhyyyhyyyss+++oooys++/://syyso
+++///:::-::yo/odMMMMMMNmhshhhddmmNNNNNNmmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNmdhdhydyhdmNMMMmmdhyysooysoooohddmNNddy/+hmmdh
END
str3 = <<END
 _______  __   __  _______  __    _  _______ 
|       ||  | |  ||   _   ||  |  | ||       |
|  _____||  |_|  ||  |_|  ||   |_| ||    ___|
| |_____ |       ||       ||       ||   |___ 
|_____  ||       ||       ||  _    ||    ___|
 _____| ||   _   ||   _   || | |   ||   |___ 
|_______||__| |__||__| |__||_|  |__||_______|
 _______  __    _  ______                    
|   _   ||  |  | ||      |                   
|  |_|  ||   |_| ||  _    |                  
|       ||       || | |   |                  
|       ||  _    || |_|   |                  
|   _   || | |   ||       |                  
|__| |__||_|  |__||______|                   
 ___      __   __  ___   _______             
|   |    |  | |  ||   | |       |            
|   |    |  | |  ||   | |  _____|            
|   |    |  |_|  ||   | | |_____             
|   |___ |       ||   | |_____  |            
|       ||       ||   |  _____| |            
|_______||_______||___| |_______|  
END
str4 = <<END
 ___      __   __  ___   _______             
|   |    |  | |  ||   | |       |            
|   |    |  | |  ||   | |  _____|            
|   |    |  |_|  ||   | | |_____             
|   |___ |       ||   | |_____  |            
|       ||       ||   |  _____| |            
|_______||_______||___| |_______|            
 _______  __    _  ______                    
|   _   ||  |  | ||      |                   
|  |_|  ||   |_| ||  _    |                  
|       ||       || | |   |                  
|       ||  _    || |_|   |                  
|   _   || | |   ||       |                  
|__| |__||_|  |__||______|                   
 _______  __   __  _______  __    _  _______ 
|       ||  | |  ||   _   ||  |  | ||       |
|  _____||  |_|  ||  |_|  ||   |_| ||    ___|
| |_____ |       ||       ||       ||   |___ 
|_____  ||       ||       ||  _    ||    ___|
 _____| ||   _   ||   _   || | |   ||   |___ 
|_______||__| |__||__| |__||_|  |__||_______|
END
str5 = <<END
 __   __  _______  _______  _______  _______  ______    _______                          
|  |_|  ||   _   ||       ||       ||       ||    _ |  |       |                         
|       ||  |_|  ||  _____||_     _||    ___||   | ||  |  _____|                         
|       ||       || |_____   |   |  |   |___ |   |_||_ | |_____                          
|       ||       ||_____  |  |   |  |    ___||    __  ||_____  |                         
| ||_|| ||   _   | _____| |  |   |  |   |___ |   |  | | _____| |                         
|_|   |_||__| |__||_______|  |___|  |_______||___|  |_||_______|                         
 _______  _______                                                                        
|       ||       |                                                                       
|   _   ||    ___|                                                                       
|  | |  ||   |___                                                                        
|  |_|  ||    ___|                                                                       
|       ||   |                                                                           
|_______||___|                                                                           
 _______  __   __  ___   _______  _______  __   __    _______  _______  ______   _______ 
|       ||  | |  ||   | |       ||       ||  | |  |  |       ||       ||      | |       |
|  _____||  |_|  ||   | |_     _||_     _||  |_|  |  |       ||   _   ||  _    ||    ___|
| |_____ |       ||   |   |   |    |   |  |       |  |       ||  | |  || | |   ||   |___ 
|_____  ||       ||   |   |   |    |   |  |_     _|  |      _||  |_|  || |_|   ||    ___|
 _____| ||   _   ||   |   |   |    |   |    |   |    |     |_ |       ||       ||   |___ 
|_______||__| |__||___|   |___|    |___|    |___|    |_______||_______||______| |_______|
END
puts `clear`
puts str3
sleep 1
puts `clear`
puts str2
sleep 0.5
puts `clear`
puts str
sleep 0.5
puts `clear`
puts str4
sleep 1
puts `clear`
puts str
sleep 0.5
puts `clear`
puts str2
sleep 0.5
puts `clear`
puts str5
sleep 2
puts `clear`
puts "Happy Kwanza! "
