#!/usr/bin/env ruby

=begin
Disk Used is a sum of all partitions calculated in Gigabytes

Disk Used Percentage is a total percentage of all disk partitions used

CPU Used is a percentage of current CPU being used

TCP/UDP Connections Used is a total count of each respectively

Active Memory Used is a percentage of active system memory being used

Load is the average load of the past minute

Bandwidth is current received and transmitted in Megabits

Disk IO is current disk reads and writes completed per second

Top Ten Processes By CPU Consumption are based on percent CPU used

Top Ten Processes By Memory Consumption are base on percent Memory used
=end

#-----------------------------------------------------------------------
#-----------------------------------------------------------------------


require 'usagewatch'
require 'pp'

usw = Usagewatch

pp usw.uw_diskused
pp usw.uw_diskused_perc
pp usw.uw_cpuused
pp usw.uw_tcpused
pp usw.uw_udpused
pp usw.uw_memused
pp usw.uw_load
pp usw.uw_bandrx
pp usw.uw_bandtx
pp usw.uw_diskioreads
pp usw.uw_diskiowrites
pp usw.uw_cputop
pp usw.uw_memtop

