#!/usr/bin/env ruby
#Written by Luis Hernando Giraldo Montiel
#This script automatically runs through an image export process (VMDK)

require 'pp'

puts `clear`
$zfs_short = `zfs list` 

puts $zfs_short

print "Please input the dataset name: "
dataset = gets.chomp.gsub(" ", "")

$zfs_data = system("zfs list -t all -r -o name,written,refer,available,creation,sync:devsnap #{dataset}")

puts ("\n")
puts "Example: 10.10.0.6@123456789 "
puts ("\n")
print "Please input agent@epoch: "
snapshot = gets.chomp.gsub(" ", "")
snapshot1 = snapshot.gsub(/@/, "-")

$zfs_clone = system("zfs clone homePool/home/agents/#{snapshot} homePool/#{snapshot1}-rubyEXPORTmanual")
$zfs_hir = system("snapctl agent:hir /homePool/#{snapshot1}-rubyEXPORTmanual")

puts "Appending to /etc/exports >"

spinner = Enumerator.new do |e|
  loop do
    e.yield '|'
    e.yield '/'
    e.yield '-'
    e.yield '\\'
  end
end

1.upto(100) do |i|
  progress = "=" * (i/5) unless i < 5
  printf("\rProgress: [%-20s] %d%% %s", progress, i, spinner.next)
  sleep(0.1)
end

$zfs_fsid = `echo -n /homePool/#{snapshot1}-rubyEXPORTmanual | md5sum`.gsub!(" ", "").gsub!("-", "").gsub!("\n", "")
File.open("/etc/exports", "a") do |output|
output.puts "/homePool/#{snapshot1}-rubyEXPORTmanual 0.0.0.0/0.0.0.0(rw,no_root_squash,no_subtree_check,insecure,fsid=#{$zfs_fsid})"
end

puts `exportfs -ra`

puts "Complete::Success"
